name = "" # todo
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "0.0.11"

[build]
command = "cargo install --git https://github.com/CathalMullan/workers-rs worker-build && worker-build --release"
